### ISSUE TITLE
Feedback on assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/r-python-exercise1-abhishekdeore#1]
Hi Abhishek, 

Really great work on the assignment. No issues. Please keep the format of the submission in mind for future assignments. 

Full credit, no edits needed.
-Greg

**Comment by abhishekdeore** [comment]
Hi Greg,
Thank you for your positive feedback! I'm glad to hear that you found the assignment satisfactory. I'll certainly keep the submission format in mind for future assignments.
